// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Theme$Reasoner from "./Theme.bs.js";
import * as Utils$Reasoner from "./Utils.bs.js";
import * as Landing$Reasoner from "./Landing.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as Reasoner$Reasoner from "./Reasoner.bs.js";

var container = Css.style(/* :: */[
      Css.fontFamily("Segoe UI, Roboto, Monaco, Helvetica, sans-serif"),
      /* :: */[
        Css.display(/* flex */-1010954439),
        /* :: */[
          Css.backgroundColor(Theme$Reasoner.Colors.background),
          /* :: */[
            Css.alignItems(/* center */98248149),
            /* :: */[
              Css.justifyContent(/* center */98248149),
              /* :: */[
                Css.height(Css.vh(100)),
                /* :: */[
                  Css.color(Theme$Reasoner.Colors.text),
                  /* :: */[
                    Css.overflow(/* hidden */-862584982),
                    /* :: */[
                      Css.padding(Css.rem(2)),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var Styles = {
  container: container
};

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  console.log(url[/* path */0]);
  var match = url[/* path */0];
  var tmp;
  var exit = 0;
  if (match) {
    switch (match[0]) {
      case "" :
          if (match[1]) {
            exit = 1;
          } else {
            tmp = React.createElement(Landing$Reasoner.make, { });
          }
          break;
      case "app" :
          if (match[1]) {
            exit = 1;
          } else {
            tmp = React.createElement(Reasoner$Reasoner.make, { });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    tmp = React.createElement(Landing$Reasoner.make, { });
  }
  if (exit === 1) {
    tmp = React.createElement("div", undefined, Utils$Reasoner.str("404 - Adrress not found"));
  }
  return React.createElement("main", {
              className: container
            }, tmp);
}

var make = App;

export {
  Styles ,
  make ,
  
}
/* container Not a pure module */
