/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const AppBS = require('./App.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Props = {};

export const make: React.ComponentType<{}> = AppBS.make;
