// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Link$Reasoner from "./Link.bs.js";
import * as Theme$Reasoner from "./Theme.bs.js";
import * as Utils$Reasoner from "./Utils.bs.js";

var logo = (require('./logo.svg'));

var container = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flex(/* `num */[
              5496390,
              1.0
            ]),
        /* :: */[
          Css.backgroundColor(Theme$Reasoner.Colors.background),
          /* [] */0
        ]
      ]
    ]);

var logo$1 = Css.style(/* :: */[
      Css.height(Css.px(0)),
      /* :: */[
        Css.animationName(Theme$Reasoner.Animations.bounceAndDisappear),
        /* :: */[
          Css.animationDuration(3000),
          /* [] */0
        ]
      ]
    ]);

var title = Css.style(/* :: */[
      Css.fontSize(Css.rem(2)),
      /* :: */[
        Css.animation(undefined, undefined, undefined, undefined, undefined, undefined, undefined, Theme$Reasoner.Animations.appear),
        /* :: */[
          Css.animationDuration(3000),
          /* :: */[
            Css.verticalAlign(/* middle */-866200747),
            /* [] */0
          ]
        ]
      ]
    ]);

var button = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.justifyContent(/* center */98248149),
        /* :: */[
          Css.alignItems(/* center */98248149),
          /* :: */[
            Css.border(Css.px(2), /* solid */12956715, Theme$Reasoner.Colors.accent),
            /* :: */[
              Css.backgroundColor(Theme$Reasoner.Colors.background),
              /* :: */[
                Css.color(Theme$Reasoner.Colors.accent),
                /* :: */[
                  Css.height(Css.rem(3.0)),
                  /* :: */[
                    Css.fontSize(Css.rem(1.0)),
                    /* :: */[
                      Css.animation(undefined, undefined, undefined, undefined, undefined, undefined, undefined, Theme$Reasoner.Animations.appear),
                      /* :: */[
                        Css.animationDuration(4000),
                        /* :: */[
                          Css.cursor(/* pointer */-786317123),
                          /* :: */[
                            Css.padding2(Css.rem(0.4), Css.rem(0.8)),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var body = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexGrow(1),
        /* :: */[
          Css.flexDirection(/* row */5693978),
          /* :: */[
            Css.alignItems(/* center */98248149),
            /* :: */[
              Css.justifyContent(/* spaceBetween */516682146),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = {
  container: container,
  logo: logo$1,
  title: title,
  button: button,
  body: body
};

function Landing$Button(Props) {
  var children = Props.children;
  return React.createElement("button", {
              className: button
            }, children);
}

var Button = {
  make: Landing$Button
};

function Landing(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("img", {
                  className: logo$1,
                  src: logo
                }), React.createElement("div", {
                  className: container
                }, React.createElement("div", {
                      className: body
                    }, React.createElement("h1", {
                          className: title
                        }, Utils$Reasoner.str("Reasoner")), React.createElement(Link$Reasoner.make, {
                          path: "app",
                          className: button,
                          children: Utils$Reasoner.str("Get start here")
                        }))));
}

var make = Landing;

export {
  logo ,
  Styles ,
  Button ,
  make ,
  
}
/* logo Not a pure module */
