// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function fromMinutes(minutes) {
  return {
          miliseconds: 0,
          seconds: 0,
          minutes: minutes,
          hours: 0
        };
}

export {
  fromMinutes ,
  
}
/* No side effect */
