// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Theme$Reasoner from "./Theme.bs.js";
import * as Utils$Reasoner from "./Utils.bs.js";

var container = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flex(/* `num */[
              5496390,
              1.0
            ]),
        /* :: */[
          Css.flexDirection(/* column */-963948842),
          /* :: */[
            Css.border(Css.px(2), /* solid */12956715, Theme$Reasoner.Colors.accent),
            /* :: */[
              Css.alignSelf(/* start */67859554),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var title = Css.style(/* :: */[
      Css.fontSize(Css.rem(2)),
      /* :: */[
        Css.verticalAlign(/* middle */-866200747),
        /* [] */0
      ]
    ]);

var Styles = {
  container: container,
  title: title
};

function Reasoner$Display(Props) {
  return React.createElement("div", undefined, Utils$Reasoner.str("display"));
}

var Display = {
  make: Reasoner$Display
};

function Reasoner$Controls(Props) {
  return React.createElement("div", undefined, Utils$Reasoner.str("Controls"));
}

var Controls = {
  make: Reasoner$Controls
};

function Reasoner(Props) {
  return React.createElement("div", {
              className: container
            }, React.createElement("h1", {
                  className: title
                }, Utils$Reasoner.str("Reasoner")), React.createElement(Reasoner$Display, { }), React.createElement(Reasoner$Controls, { }));
}

var make = Reasoner;

export {
  Styles ,
  Display ,
  Controls ,
  make ,
  
}
/* container Not a pure module */
