// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var primary = Css.hex("6200EE");

var background = Css.hex("282c34");

var accent = Css.hex("09d3ac");

var surface = Css.hex("FFF");

var text = Css.hex("EEE");

var error = Css.hex("B00020");

var Colors = {
  primary: primary,
  background: background,
  accent: accent,
  surface: surface,
  text: text,
  error: error
};

var Fonts = {
  text: "Montserrat",
  display: "Fredericka the Great"
};

var borderWidth = Css.rem(0.1);

var bounce = Css.keyframes(/* :: */[
      /* tuple */[
        0,
        /* :: */[
          Css.transform(Css.scale(0.1, 0.1)),
          /* :: */[
            Css.opacity(0.0),
            /* [] */0
          ]
        ]
      ],
      /* :: */[
        /* tuple */[
          60,
          /* :: */[
            Css.transform(Css.scale(1.2, 1.2)),
            /* :: */[
              Css.opacity(1.0),
              /* [] */0
            ]
          ]
        ],
        /* :: */[
          /* tuple */[
            100,
            /* :: */[
              Css.transform(Css.scale(1.0, 1.0)),
              /* :: */[
                Css.opacity(1.0),
                /* [] */0
              ]
            ]
          ],
          /* [] */0
        ]
      ]
    ]);

function bounceAndDisappear(height$prime) {
  return Css.keyframes(/* :: */[
              /* tuple */[
                0,
                /* :: */[
                  Css.height(height$prime),
                  /* :: */[
                    Css.transform(Css.scale(0.1, 0.1)),
                    /* :: */[
                      Css.opacity(0.0),
                      /* [] */0
                    ]
                  ]
                ]
              ],
              /* :: */[
                /* tuple */[
                  50,
                  /* :: */[
                    Css.transform(Css.scale(1.2, 1.2)),
                    /* :: */[
                      Css.opacity(1.0),
                      /* [] */0
                    ]
                  ]
                ],
                /* :: */[
                  /* tuple */[
                    100,
                    /* :: */[
                      Css.transform(Css.scale(0.0, 0.0)),
                      /* :: */[
                        Css.opacity(0.0),
                        /* :: */[
                          Css.height(/* zero */-789508312),
                          /* [] */0
                        ]
                      ]
                    ]
                  ],
                  /* [] */0
                ]
              ]
            ]);
}

var fadeIn = Css.keyframes(/* :: */[
      /* tuple */[
        0,
        /* :: */[
          Css.opacity(0.0),
          /* [] */0
        ]
      ],
      /* :: */[
        /* tuple */[
          100,
          /* :: */[
            Css.opacity(1.0),
            /* [] */0
          ]
        ],
        /* [] */0
      ]
    ]);

function letterFadeOut(fontSize$prime) {
  return Css.keyframes(/* :: */[
              /* tuple */[
                0,
                /* :: */[
                  Css.opacity(0.0),
                  /* :: */[
                    Css.fontSize(fontSize$prime),
                    /* [] */0
                  ]
                ]
              ],
              /* :: */[
                /* tuple */[
                  30,
                  /* :: */[
                    Css.opacity(0.0),
                    /* [] */0
                  ]
                ],
                /* :: */[
                  /* tuple */[
                    60,
                    /* :: */[
                      Css.opacity(0.1),
                      /* :: */[
                        Css.color(Css.white),
                        /* [] */0
                      ]
                    ]
                  ],
                  /* :: */[
                    /* tuple */[
                      90,
                      /* :: */[
                        Css.opacity(1.0),
                        /* :: */[
                          Css.fontSize(fontSize$prime),
                          /* [] */0
                        ]
                      ]
                    ],
                    /* :: */[
                      /* tuple */[
                        91,
                        /* :: */[
                          Css.opacity(0.0),
                          /* :: */[
                            Css.fontSize(fontSize$prime),
                            /* :: */[
                              Css.color(Css.red),
                              /* [] */0
                            ]
                          ]
                        ]
                      ],
                      /* :: */[
                        /* tuple */[
                          100,
                          /* :: */[
                            Css.opacity(0.0),
                            /* :: */[
                              Css.fontSize(/* zero */-789508312),
                              /* [] */0
                            ]
                          ]
                        ],
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var appear = Css.keyframes(/* :: */[
      /* tuple */[
        0,
        /* :: */[
          Css.opacity(0.0),
          /* [] */0
        ]
      ],
      /* :: */[
        /* tuple */[
          30,
          /* :: */[
            Css.opacity(0.0),
            /* [] */0
          ]
        ],
        /* :: */[
          /* tuple */[
            60,
            /* :: */[
              Css.opacity(0.1),
              /* [] */0
            ]
          ],
          /* :: */[
            /* tuple */[
              100,
              /* :: */[
                Css.opacity(1.0),
                /* [] */0
              ]
            ],
            /* [] */0
          ]
        ]
      ]
    ]);

var Animations = {
  bounce: bounce,
  bounceAndDisappear: bounceAndDisappear,
  fadeIn: fadeIn,
  letterFadeOut: letterFadeOut,
  appear: appear
};

export {
  Colors ,
  Fonts ,
  borderWidth ,
  Animations ,
  
}
/* primary Not a pure module */
