// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function TimePicker(Props, value, onChange, className) {
  return React.createElement("input", {
              className: className,
              value: value,
              onChange: onChange
            });
}

var make = TimePicker;

export {
  make ,
  
}
/* react Not a pure module */
