// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as $$String from "bs-platform/lib/es6/string.js";
import * as Caml_string from "bs-platform/lib/es6/caml_string.js";

function str(prim) {
  return prim;
}

function arr(prim) {
  return prim;
}

function split(s) {
  return List.map((function (s) {
                return $$String.make(1, Caml_string.get(s, 0));
              }), $$Array.to_list(s.split("")));
}

export {
  str ,
  arr ,
  split ,
  
}
/* No side effect */
